name: Graphviz CI
on: [push]
jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: font get
        run: sudo apt-get install fonts-takao-mincho fonts-takao
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: npm ci
        run: npm ci
      - name: generate png from pu
        run: npm run generate-png
      - name: Count changes
        id: changes
        run: |
          git add -N . # 新規ファイルを含める
          echo "::set-output name=count::$(git diff --name-only | wc -l)"
      - name: commit & push
        env:
        run: |
          git add .
          git commit -m "Update"
          git pull origin main
          git push origin main
        if: steps.changes.outputs.count > 0
