name: Graphviz CI
on: [push]
jobs:
  test:
    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: npm ci
        run: npm ci
      - name: generate png from pu
        run: npm run generate-png
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update"
          git push
        if: steps.changes.outputs.count > 0
